services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Taipei
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --default-time-zone="+08:00"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  # Python
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - TZ=Asia/Taipei

  # Vue
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - web

  # Vue management application
  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile
    volumes:
      - ./admin-frontend:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - web

  # redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
