"""update price and duration column name

Revision ID: 2b636100d568
Revises: 369f73fb8113
Create Date: 2026-04-27 05:03:58.227015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b636100d568'
down_revision: Union[str, Sequence[str], None] = '369f73fb8113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('total_price', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('total_duration', sa.Integer(), nullable=True))
    op.drop_column('appointments', 'price_at_transaction')
    op.drop_column('appointments', 'duration_at_transaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('duration_at_transaction', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('price_at_transaction', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'total_duration')
    op.drop_column('appointments', 'total_price')
    # ### end Alembic commands ###
