"""update client user_id to line_user_id

Revision ID: 369f73fb8113
Revises: c734eefb415d
Create Date: 2026-04-27 04:54:49.347250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '369f73fb8113'
down_revision: Union[str, Sequence[str], None] = 'c734eefb415d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('line_user_id', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.create_index(op.f('ix_clients_line_user_id'), 'clients', ['line_user_id'], unique=True)
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_index(op.f('ix_clients_line_user_id'), table_name='clients')
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=True)
    op.drop_column('clients', 'line_user_id')
    # ### end Alembic commands ###
