"""name_to_last_name_and_first_name_column

Revision ID: 38ce518b7cbe
Revises: c4ab74ed76c4
Create Date: 2026-05-05 15:23:31.317586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy import table, column

# revision identifiers, used by Alembic.
revision: str = '38ce518b7cbe'
down_revision: Union[str, Sequence[str], None] = 'c4ab74ed76c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('first_name', sa.String(length=50), nullable=True))
    
    bind = op.get_bind()
    session = Session(bind=bind)
    
    # 宣告我們要用的欄位
    clients_helper = table('clients',
        column('id', sa.Integer),
        column('name', sa.String),
        column('last_name', sa.String),
        column('first_name', sa.String)
    )

    # 取得所有舊資料
    all_clients = session.execute(sa.select(clients_helper)).all()

    for client in all_clients:
        old_name = client.name if client.name else ""
        
        # 中文姓名拆分邏輯：第一個字為姓，其餘為名
        # 注意：這是一個通用邏輯，若有複姓（如司馬）需手動調整
        if len(old_name) >= 2:
            ln = old_name[0]      # 姓
            fn = old_name[1:]     # 名
        else:
            ln = old_name         # 若只有一個字，暫時放在姓
            fn = ""

        # 更新資料
        session.execute(
            sa.update(clients_helper)
            .where(clients_helper.c.id == client.id)
            .values(last_name=ln, first_name=fn)
        )
    
    session.commit()

    op.alter_column('clients', 'last_name', 
                    nullable=False, 
                    type_=sa.String(length=50))
    op.alter_column('clients', 'first_name', 
                    nullable=False, 
                    type_=sa.String(length=50))
    
    op.drop_column('clients', 'name')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.String(length=255), nullable=True))
    bind = op.get_bind()
    session = Session(bind=bind)
    clients_helper = table('clients',
        column('id', sa.Integer),
        column('name', sa.String),
        column('last_name', sa.String),
        column('first_name', sa.String)
    )
    
    all_clients = session.execute(sa.select(clients_helper)).all()
    for client in all_clients:
        session.execute(
            sa.update(clients_helper)
            .where(clients_helper.c.id == client.id)
            .values(name=f"{client.last_name}{client.first_name}")
        )
    session.commit()

    # 3. 移除新欄位
    op.drop_column('clients', 'first_name')
    op.drop_column('clients', 'last_name')
    # ### end Alembic commands ###
