"""add_categories_and_link_services

Revision ID: 5e8fdc60666e
Revises: 9b2d29136ab2
Create Date: 2026-05-05 12:52:42.430117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e8fdc60666e'
down_revision: Union[str, Sequence[str], None] = '9b2d29136ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_name', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_charset='utf8mb4',
        mysql_collate='utf8mb4_unicode_ci'
    )
    
    op.add_column('services', sa.Column('category_id', sa.Integer(), nullable=True))
    
    categories_table = sa.table('categories', sa.column('id'), sa.column('category_name'))
    op.bulk_insert(
        categories_table,
        [
            {'id': 1, 'category_name': '阿卡西解讀'},
            {'id': 2, 'category_name': '頌缽'}
        ]
    )

    op.execute("UPDATE services SET category_id = 2 WHERE service_name = '頌缽療癒'")
    op.execute("UPDATE services SET category_id = 1 WHERE category_id IS NULL")

    op.alter_column('services', 'category_id', 
               existing_type=sa.Integer(), 
               nullable=False)
    
    op.create_foreign_key('fk_services_categories', 
        'services', 'categories', 
        ['category_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_services_categories', 'services', type_='foreignkey')
    op.drop_column('services', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
