"""fix_structure_and_add_expired

Revision ID: 9b2d29136ab2
Revises: 2b636100d568
Create Date: 2026-05-01 16:25:52.516722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b2d29136ab2'
down_revision: Union[str, Sequence[str], None] = '2b636100d568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('expired', sa.Boolean(), nullable=True))
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('appointments', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('note', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_column('appointments', 'created_at')
    op.drop_column('appointments', 'expired')
    # ### end Alembic commands ###
