"""add_user_message_column_to_appointment

Revision ID: c4ab74ed76c4
Revises: 5e8fdc60666e
Create Date: 2026-05-05 13:33:28.459094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4ab74ed76c4'
down_revision: Union[str, Sequence[str], None] = '5e8fdc60666e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'service_name',
               existing_type=sa.String(length=255),
               nullable=False)

    op.add_column('appointments', sa.Column('user_message', sa.String(length=500), nullable=True))
    
    op.execute("INSERT INTO services (service_name, category_id) VALUES ('其他', 1)")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'user_message')
    op.execute("DELETE FROM services WHERE service_name = '其他' AND category_id = 1")
    op.alter_column('services', 'service_name',
               existing_type=sa.String(length=255),
               nullable=True)
    # ### end Alembic commands ###
