"""move price and duration to appointment

Revision ID: c734eefb415d
Revises: aad34cb812aa
Create Date: 2026-04-27 04:44:30.579954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c734eefb415d'
down_revision: Union[str, Sequence[str], None] = 'aad34cb812aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_items', 'duration_at_transaction')
    op.drop_column('appointment_items', 'price_at_transaction')
    op.add_column('appointments', sa.Column('price_at_transaction', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('duration_at_transaction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'duration_at_transaction')
    op.drop_column('appointments', 'price_at_transaction')
    op.add_column('appointment_items', sa.Column('price_at_transaction', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('appointment_items', sa.Column('duration_at_transaction', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
